Fix Godot CLI arguments to use `--headless` everywhere
abarichello/godot-ci pull request #113
Opened 2023-06-12 16:01 UTC by Calinou

- Use long-form `--verbose` and `--editor` for better readability.

___

- This closes https://github.com/abarichello/godot-ci/issues/112.

2023-06-13 20:04 UTC, OverloadedOrama commented
`--headless` doesn't exist in Godot 3.x, right? test-project seems to be a Godot 3.x project, and `GODOT_VERSION` is set to 3.3.4. Maybe the test project should be updated to Godot 4.x as well?

2023-06-13 20:50 UTC, Calinou commented
> 

Ah, I didn't notice that. In any case, unknown CLI arguments are ignored, so this change is backwards-compatible.

2023-12-19 06:57 UTC, Towfieee requested changes

2023-12-19 06:57 UTC, Towfieee commented on .github/workflows/godot-ci.yml
> +          godot --headless --verbose --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
I believe `--export` has been deprecated. It is now an explicit `--export-release`, `--export-debug`, or `--export-pack`. There are multiple references to this deprecated flag in this file.

reference: https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html

2023-12-21 06:34 UTC, Towfieee approved these changes

2023-12-21 16:43 UTC, merged